config:
  send_anonymous_usage_stats: False
  use_colors: True
  partial_parse: True


test_project:
  outputs:
    dev:
      type: postgres
      threads: 3
      host: postgres
      port: 5432
      user: airflow
      pass: "airflow"
      dbname: airflow
      schema: public
  target: dev